services:
  web:
    build: .
    container_name: earlypass-web
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_SECRET_KEY: "change-me-in-prod"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    command: ["gunicorn", "earlypass.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
