# Generated by Django 5.2.7 on 2025-10-21 21:53

import passes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0004_proposedclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedclass',
            name='deadline',
            field=models.DateTimeField(default=passes.models.default_proposed_deadline, help_text='Submission deadline for this class'),
        ),
        migrations.AddField(
            model_name='proposedclass',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of what students need to do to pass this class'),
        ),
    ]
