# Generated by Django 5.2.7 on 2025-10-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0005_proposedclass_deadline_proposedclass_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Requirements to pass this class'),
        ),
    ]
